### ISSUE TITLE
update eslint-plugin-promise

### ISSUE THREAD

**Issue by dlmanning** [ZHealth/eslint-config-esmanning#1]
The current version of eslint-config-standard (6.2.1) has a peer dependency (yuck) of eslint-plugin-promise >= 3.3.0

We currently install ^2.0.1

**Comment by bcomnes** [comment]
wooops

**Comment by ungoldman** [comment]
oh snap, that's not Manning Style. will fix soon

**Comment by ungoldman** [comment]
it fix

**Comment by ungoldman** [comment]
fix published in [1.0.1](https://github.com/ZHealth/eslint-config-esmanning/releases/tag/v1.0.1)
